import { setToken } from './tokenStore';

function getHashToken(hash: string): string | null {
  const rawHash = hash.startsWith('#') ? hash.slice(1) : hash;
  if (!rawHash) return null;

  if (rawHash.startsWith('access_token=')) {
    return new URLSearchParams(rawHash).get('access_token');
  }

  const queryIndex = rawHash.indexOf('?');
  if (queryIndex >= 0) {
    return new URLSearchParams(rawHash.slice(queryIndex + 1)).get('access_token');
  }

  const legacyMatch = rawHash.match(/(?:^|&)access_token=([^&]+)/);
  return legacyMatch ? decodeURIComponent(legacyMatch[1]) : null;
}

function getUrlToken(): string | null {
  return new URLSearchParams(window.location.search).get('access_token') ?? getHashToken(window.location.hash);
}

function stripAccessTokenFromSearch(search: string): string {
  const params = new URLSearchParams(search);
  params.delete('access_token');
  const nextSearch = params.toString();
  return nextSearch ? `?${nextSearch}` : '';
}

function stripAccessTokenFromHash(hash: string): string {
  if (!hash.startsWith('#/')) {
    return '#/dashboard';
  }

  const rawHash = hash.slice(1);
  const [pathPart, query = ''] = rawHash.split('?');
  const params = new URLSearchParams(query);
  params.delete('access_token');
  const nextQuery = params.toString();
  return `#${pathPart || '/dashboard'}${nextQuery ? `?${nextQuery}` : ''}`;
}

const urlToken = getUrlToken();
const devToken = (window as any).__DEV_TOKEN__;
// The host-provided URL token always wins: __DEV_TOKEN__ is injected by the
// dev server only and may reference a token from an earlier backend session,
// while the URL token is regenerated by the host on every backend (re)start.
const activeToken = urlToken ?? devToken;

if (activeToken) {
  setToken(activeToken);
}

if (urlToken) {
  const nextUrl = `${window.location.pathname}${stripAccessTokenFromSearch(window.location.search)}${stripAccessTokenFromHash(window.location.hash)}`;
  window.history.replaceState(null, '', nextUrl);
}
