#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import unittest
from datetime import date
from pathlib import Path
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parent))

from llm_transport import _extract_json_candidate, call_llm, call_llm_json
from state_ops import DEFAULT_SINGLE_AREA_NAME


TEST_CONFIG = {
    "base_url": "http://127.0.0.1:11434/v1",
    "model": "unit-test-model",
    "api_key": "",
    "llm_stream": False,
}


class TestLlmTransportStructuredParsing(unittest.TestCase):
    def test_extract_json_candidate_ignores_reasoning_blocks(self):
        content = """
<think>
I should first inspect this draft payload: {"debug": true}
</think>
```json
{"status": "ok", "count": 2}
```
"""
        parsed = _extract_json_candidate(content)
        self.assertEqual(parsed["status"], "ok")
        self.assertEqual(parsed["count"], 2)

    @patch("llm_transport.call_llm_raw")
    def test_call_llm_json_ignores_reasoning_blocks(self, mock_call_llm_raw):
        mock_call_llm_raw.return_value = """
<thinking>
Need to think first. {"noise": 1}
</thinking>
<json>{"result": "success", "items": [1, 2]}</json>
"""

        parsed, raw_text = call_llm_json(
            [{"role": "user", "content": "Return JSON"}],
            TEST_CONFIG,
        )

        self.assertEqual(parsed["result"], "success")
        self.assertEqual(parsed["items"], [1, 2])
        self.assertIn("<thinking>", raw_text)

    @patch("llm_transport.call_llm_raw")
    def test_call_llm_parses_hash_comment_note(self, mock_call_llm_raw):
        mock_call_llm_raw.return_value = """
<think>
draft only
</think>
[areas]
A = Classroom
B = Cleaning
S = SpecialCleanup
[schedule]
03-24 = A:1001 1002 | B:1003 1004
03-28 = A:1009 1010 | B:1011 1012 | S:1013 1014 # Friday cleanup
[state]
debt = 1004*2 1005
credit = 1002
"""

        parsed, raw_text = call_llm(
            [{"role": "user", "content": "Return V2"}],
            TEST_CONFIG,
            start_date_value=date(2026, 3, 24),
        )

        self.assertEqual(len(parsed["schedule"]), 2)
        self.assertEqual(parsed["schedule"][0]["date"], "2026-03-24")
        self.assertEqual(parsed["schedule"][1]["area_ids"]["SpecialCleanup"], [1013, 1014])
        self.assertEqual(parsed["schedule"][1]["note"], "Friday cleanup")
        self.assertEqual(parsed["state_delta"]["debt_counts"], {1004: 2, 1005: 1})
        self.assertEqual(parsed["state_delta"]["credit_counts"], {1002: 1})
        self.assertIn("<think>", raw_text)

    @patch("llm_transport.call_llm_raw")
    def test_call_llm_rejects_legacy_note_field(self, mock_call_llm_raw):
        mock_call_llm_raw.return_value = """
[areas]
A = Classroom

[schedule]
03-24 = A:1001 | _note:bad
"""
        with self.assertRaisesRegex(RuntimeError, "unknown area alias _note"):
            call_llm(
                [{"role": "user", "content": "Return V2"}],
                TEST_CONFIG,
                start_date_value=date(2026, 3, 24),
            )

    @patch("llm_transport.call_llm_raw")
    def test_call_llm_ignores_ini_comment_lines(self, mock_call_llm_raw):
        mock_call_llm_raw.return_value = """
# generated by model
[areas]
; alias table
A = Duty

[schedule]
; first workday
03-24 = A:1001 1002 # regular pair
"""

        parsed, _ = call_llm(
            [{"role": "user", "content": "Return V2"}],
            TEST_CONFIG,
            start_date_value=date(2026, 3, 24),
        )

        self.assertEqual(parsed["schedule"][0]["date"], "2026-03-24")
        self.assertEqual(parsed["schedule"][0]["area_ids"]["Duty"], [1001, 1002])
        self.assertEqual(parsed["schedule"][0]["note"], "regular pair")

    @patch("llm_transport.call_llm_raw")
    def test_call_llm_keeps_legacy_assigned_ids_as_single_area_fallback(self, mock_call_llm_raw):
        mock_call_llm_raw.return_value = """
<csv>
Date,Assigned_IDs,Note
2026-03-22,1004,Legacy
</csv>
"""

        parsed, _ = call_llm(
            [{"role": "user", "content": "Return CSV"}],
            TEST_CONFIG,
            start_date_value=date(2026, 3, 22),
        )

        self.assertEqual(parsed["schedule"][0]["area_ids"][DEFAULT_SINGLE_AREA_NAME], "1004")
        self.assertEqual(parsed["state_delta"]["debt_counts"], {})
        self.assertEqual(parsed["state_delta"]["credit_counts"], {})

    @patch("llm_transport.call_llm_raw")
    def test_call_llm_handles_cross_year_mmdd(self, mock_call_llm_raw):
        mock_call_llm_raw.return_value = """
[areas]
A = Duty

[schedule]
12-31 = A:1001
01-02 = A:1002
"""

        parsed, _ = call_llm(
            [{"role": "user", "content": "Return V2"}],
            TEST_CONFIG,
            start_date_value=date(2026, 12, 31),
        )

        self.assertEqual(parsed["schedule"][0]["date"], "2026-12-31")
        self.assertEqual(parsed["schedule"][1]["date"], "2027-01-02")

    @patch("llm_transport.call_llm_raw")
    def test_call_llm_uses_last_complete_plan_when_multiple_plans_exist(self, mock_call_llm_raw):
        mock_call_llm_raw.return_value = """
Draft plan:
[areas]
A = Classroom
[schedule]
03-24 = A:1001

Final plan:
[areas]
A = Classroom
B = Cleaning
[schedule]
03-24 = A:2001 2002 | B:2003 2004 # final
"""

        parsed, _ = call_llm(
            [{"role": "user", "content": "Return V2"}],
            TEST_CONFIG,
            start_date_value=date(2026, 3, 24),
        )

        self.assertEqual(parsed["schedule"][0]["area_ids"]["Classroom"], [2001, 2002])
        self.assertEqual(parsed["schedule"][0]["area_ids"]["Cleaning"], [2003, 2004])
        self.assertEqual(parsed["schedule"][0]["note"], "final")


if __name__ == "__main__":
    unittest.main()
