/**
 * 从 src/theme/tokens.json 生成 src/styles/tokens.generated.css。
 * dev / build 前自动执行(package.json predev / prebuild),生成文件进 git。
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const data = JSON.parse(readFileSync(resolve(root, 'src/theme/tokens.json'), 'utf-8'));
const outPath = resolve(root, 'src/styles/tokens.generated.css');

const kebab = (key) => key
  .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
  .replace(/([a-z])(\d)/g, '$1-$2')
  .toLowerCase();

function themeBlock(theme, { selector, colorScheme, shadowOverlay }) {
  return [
    `${selector} {`,
    `  color-scheme: ${colorScheme};`,
    ...Object.entries(theme).map(([k, v]) => `  --dt-${kebab(k)}: ${v};`),
    `  --dt-font-sans: ${data.meta.fontFamily};`,
    `  --dt-radius: ${data.meta.radiusControl}px;`,
    `  --dt-radius-lg: ${data.meta.radiusPanel}px;`,
    `  --dt-radius-xl: ${data.meta.radiusOverlay}px;`,
    `  --dt-shadow-overlay: ${shadowOverlay};`,
    `  --dt-shadow-subtle: ${data.meta.shadowSubtle};`,
    '}',
  ].join('\n');
}

const css = [
  '/* AUTO-GENERATED by scripts/gen-tokens.mjs — 源头是 src/theme/tokens.json,不要手改 */',
  themeBlock(data.light, { selector: ':root,\n[data-theme=\'light\']', colorScheme: 'light', shadowOverlay: data.meta.shadowOverlay }),
  '',
  themeBlock(data.dark, { selector: '[data-theme=\'dark\']', colorScheme: 'dark', shadowOverlay: data.meta.shadowOverlayDark }),
  '',
].join('\n');

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, css);
console.log(`[gen-tokens] wrote ${outPath}`);
